###
### Notes
###
### The travis web interface may choke silently and fail to
### update when there are issues with the .travis.yml file.
###
### The "travis-lint" command-line tool does not catch all
### errors which may lead to silent failure.
###
### Shell-style comments in this file must have "#" as the
### *first* character of the line.
###

###
### language
###

language: emacs-lisp

###
### defining the build matrix
###
### ===>                                                       <===
### ===> each variation in env/matrix will be built and tested <===
### ===>                                                       <===
###
### variables under env/global are available to the build process
### but don't cause the creation of a separate variation
###

###
### limit build attempts to defined branches
###
### notes
###
### This controls which branches are built.
###
### You can also control which branches affect the web badge, by
### appending "?branch=master,staging,production" to the end of the
### image URL (replacing "master,staging,production" with a
### comma-separated list of branches to be reflected in the badge).
###
#
#  branches:
#    only:
#      - master
#

###
### runtime initialization
###

before_install:
  - git submodule --quiet update --init --recursive
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python;
  - export PATH="${HOME}/.cask/bin:$PATH"

install:
  - sudo add-apt-repository -y ppa:cassou/emacs &&
    sudo apt-get -qq update &&
    sudo apt-get -qq -f install &&
    sudo apt-get -qq install emacs24 emacs24-el

before_script:
  - make downloads

###
### the actual build/test command
###
### (use "make test-batch" to test without byte-compiling)
###

script:
  make test

###
### settings
###

notifications:
  email: false

#
# Emacs
#
# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
#
