###
### Notes
###
### The travis web interface may choke silently and fail to
### update when there are issues with the .travis.yml file.
###
### The "travis-lint" command-line tool does not catch all
### errors which may lead to silent failure.
###
### Shell-style comments in this file must have "#" as the
### *first* character of the line.
###

sudo: false

###
### language
###

language: emacs-lisp

###
### limit build attempts to defined branches
###
### notes
###
### This controls which branches are built.
###
### You can also control which branches affect the web badge, by
### appending "?branch=master,staging,production" to the end of the
### image URL (replacing "master,staging,production" with a
### comma-separated list of branches to be reflected in the badge).
###
#
#  branches:
#    only:
#      - master
#

###
### runtime initialization
###

addons:
  apt:
    sources:
      - cassou-emacs
    packages:
      - emacs24

before_install:
  - git submodule --quiet update --init --recursive
  - git config --global user.email "noemail@noemail.com"
  - git config --global user.name "noname"

install:
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python;
  - export PATH="${HOME}/.cask/bin:$PATH"

before_script:
  - make downloads

###
### the actual build/test command
###
### (use "make test-batch" to test without byte-compiling)
###

script:
  make test

###
### settings
###

notifications:
  email: false

#
# Emacs
#
# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
#
